services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/paramedic
      - JWT_SECRET=52951d6c8c4041ca7c7122c49824c6821b9e0b8b3b664b7d98ba3a88839b994825a661828218d939527c09de5711847df86ef46b4778fc44dca4f26d0f204e20
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongo_data:
